GROUP-THR3E/AJExchange

public/css/style.css
src/Views/_layout.phtml
src/Views/users/login.phtml

Create login frontend

---

src/Models/Listing.php
src/Models/Office.php
src/Models/User.php

Added basic routing system with controllers

---

src/Models/Listing.php
src/Models/Office.php
src/Models/User.php

Added navigation properties to models

---

public/css/style.css
src/Controllers/ListingControllers.php
src/Views/listings/view.phtml

Created ListingController and added /listings route and WIP view,

---

.gitignore
composer.json
src/Models/Listing.php
src/Models/Office.php
src/Models/User.php
src/Util/DatabaseSingleton.php
src/Util/DatasetBase.php
src/Util/ListingDataset.php
src/Util/OfficeDataset.php
src/Util/UserDataset.php

Add initial dataset classes

---

public/css/style.css
src/Controllers/ListingControllers.php
src/Views/listings/create.phtml

- Made create page frontend
- Listing controllers was updated to support create page
- Style css updated to support the create page frontend

Issue #2 - Creating listing creation page frontend

---

src/Util/ListingDataset.php

Update ListingDataset SQL to use joins

---

src/Util/ListingDataset.php

Added create function to ListingDataset

---

public/css/style.css
src/Controllers/ListingsController.php
src/Views/listings/search.phtml

Basic frontend design for Issue #5

---

src/Controllers/ListingsController.php
src/Views/listings/search.phtml

Implemented backend for search page 

---

src/Controllers/ListingsController.php
src/Views/listings/create.phtml
src/Views/listings/createSuccessful.phtml

Resolves #17
- All user inputs from the create page goes directly to the database.
- Listing Controller updated with post for the create page.
- Created a new "Create Successful" page as a Post to the create page for every successful data insertion.

Impemented Backend for Creating Listings

---

src/Views/listings/view.phtml

updated individual listing view to display different listing types

---

public/index.php
src/Controllers/UsersController.php
src/Models/User.php
src/Util/Auth.php
src/Util/UserDataset.php
src/Views/users/login.phtml

Added authentication and login

---

src/Controllers/UsersController.php
src/Util/Auth.php

Added logout function and route

---

public/index.php
src/Util/Auth.php

Added authentication and authorization to all pages

---

public/css/style.css
src/Views/listings/create.phtml
src/Views/listings/createSuccessful.phtml

Resolves #47 
- Fixed class img to be all the same "listingCreateImage" in Create Page.
- Changed outerDiv to a unique outerDiv for create listing page called "createOuterDiv".
- Removed 1-5 Image classes and replaced with 1 image class for the create listing page. (CSS)
- Removed duplicate font-size in .home-image.description.
- Removed extra unnecessary spacing in line 130 & 150

Post-Fix Listing Create Frontend + Fomatting

---

public/css/style.css
src/Views/index.phtml
src/Views/listings/create.phtml
src/Views/listings/search.phtml
src/Views/listings/view.phtml

Initial css cleanup

---

src/Constants/ListingType.php
src/Controllers/HomeController.php
src/Models/HomepageData.php
src/Util/HomeDataset.php
src/Views/index.phtml

Homepage backend

---

src/Views/listings/search.phtml

Now displays different exchange methods

Made changes to frontend search page 

---

public/css/style.css
src/Views/_layout.phtml
src/Views/index.phtml
src/Views/listings/createSuccessful.phtml
src/Views/listings/search.phtml

Added hyperlinks on text and images to index page and search page

---

src/Views/listings/create.phtml
src/Views/listings/view.phtml

dummy images for view and create

Added dummy images to pages

---

package-lock.json
public/css/style.css
src/Views/index.phtml
src/Views/users/login.phtml

Changed design and css elements of home page, login page and css file

---

.htaccess
composer.json
index.php
src/Util/DatabaseSingleton.php
src/Views/_layout.phtml

Prepare application for deployment on Apache server

---

src/Controllers/ListingsController.php
src/Views/index.phtml

Add all listings link to homepage

---

.gitignore
src/Models/Listing.php
src/Util/ListingDataset.php

Add images to model and db

---

src/Views/index.phtml
src/Views/listings/create.phtml
src/Views/listings/search.phtml
src/Views/listings/view.phtml

updated pages to sanitise user inputted data before displaying it

---

src/Controllers/ListingsController.php
src/Views/listings/search.phtml

Partially resolves #65, user can now choose the method of trading, also displays no results message

Searchpage filters

---

public/css/style.css

Fixed main image sizing on listing page

---

src/Controllers/ListingsController.php

Error message no longer appears when no filter is used.

Made changes to ListingsController.php

---

src/Controllers/ListingsController.php
src/Util/HomeDataset.php

changed search and homepage so that only approved listings are shown

---

src/Controllers/ListingsController.php

Adjusted controller so if a user tries to access a non approved item they're redirected to the home page, admins can access all items

---

src/Controllers/ListingsController.php
src/Controllers/UsersController.php
src/Util/HomeDataset.php
src/Util/ListingDataset.php
src/Views/index.phtml
src/Views/users/listings.phtml

Filtered search and home to not display own items, and added my listings page

---

src/Controllers/ListingsController.php
src/Controllers/UsersController.php
src/Views/listings/create.phtml
src/Views/users/login.phtml

#resolves 64
Form Validation includes:
-----
Backend:
- Checked if title is empty or char exceed 50
- Checked if desc is empty or char exceed 300
- Checked if either of the 3 listings types is SELECTED: elseif:
- If Sell is checked - check if empty or number exceed 100,000 or check if its a string or any other unwanted value
- If Exchange is checked - check if empty or char exceeds 50
- If Giveaway is checked - check if confirm box is checked
Frontend:
- min & max was set for title, desc, exchange
- Sell allows only positive number
Login
- Added alert for generalised wrong input login

Validation Backend/Frontend for Create & Login Page

---

public/css/style.css
src/Views/index.phtml

Remove blank icons from homepage and replaced logout homepage link with admin controls link

---

src/Models/ModelBase.php
src/Models/User.php

Fixed problems with ModelBase.php and added ability to only use single attributes of models in queries

---

src/Views/listings/search.phtml

Changed checkboxes to radiobuttons for trade method, Simplified the code for keeping radiobuttons checked on refresh

Made changes to search.phtml

---

public/css/style.css
src/Views/index.phtml

Doesn't resolve anything just styling for home page

Fixed up home page design a bit (will do more but quick fix before meeting)

---

src/Controllers/ListingsController.php
src/Views/listings/create.phtml
src/Views/users/login.phtml

resolves #102 
- Created a Charity Checkbox underneath of the Sell option to indicate that you can only send the funds to the charity.
- Dropdown with temp charities
- Listing Controller includes full validation for charity
- Removed text-center in alert for consistency
- Removed useless brackets in 3 if statements for readability

Charity Front End for Create Form:

---

src/Controllers/ListingsController.php
src/Controllers/UsersController.php
src/Models/Charity.php
src/Models/Listing.php
src/Util/CharityDataset.php
src/Util/ListingDataset.php
src/Views/listings/adminControls.phtml
src/Views/listings/create.phtml
src/Views/listings/search.phtml
src/Views/listings/view.phtml
src/Views/users/listings.phtml

Charity backend and linked data to views

---

src/Views/listings/search.phtml

resolves issue that hasn't been added to issues tab

FINALLY FIXED THE VIEW ALL LISTINGS PAGE ERRORS

---

src/Controllers/ListingsController.php

Resolves #108 
- Includes image validation
- Includes pattern for title, desc, exchange to remove unnecessary white spaces to go into the database

Image validation - Issue #108

---

public/css/style.css
src/Views/index.phtml
src/Views/listings/create.phtml
src/Views/listings/view.phtml

Mobile responsiveness

---

src/Controllers/ListingsController.php
src/Views/listings/search.phtml

Changes to ListingsController.php and search.phtml

Removes arraykey error message for admin and view all listing

---

src/Models/Listing.php
src/Models/Tag.php
src/Util/ListingDataset.php
src/Util/OrderDataset.php
src/Util/TagDataset.php

Add tags functionality to database and backend

---

public/css/style.css
src/Controllers/ListingsController.php
src/Views/listings/create.phtml

Resolves #116 
- Added validation for tags (Alphanumeric, Dashes, Underscore and Max 20)
- Saves Tags information if error in create
- Added Warning signs in error messages
- RENAMED Categories to Tags

Tag Validation

---

public/css/style.css
src/Views/_layout.phtml
src/Views/index.phtml
src/Views/listings/adminControls.phtml
src/Views/listings/search.phtml
src/Views/listings/view.phtml
src/Views/users/listings.phtml
src/Views/users/login.phtml
src/Views/users/orders.phtml

Home page in progress other pages are mostly done

Styling consistency for all pages

---

src/Views/_layout.phtml

REMOVED THEM HOPEFULLY IF AND ENDIF ARE IN THE CORRECT PLACE!

Removed search bar & button in login page

---

public/css/style.css

removed width from footer bottom so there is no horizontal scrolling

---

public/css/style.css
src/Views/listings/adminControls.phtml
src/Views/listings/search.phtml
src/Views/users/listings.phtml

Offcanvas implementation for filters

---

public/css/style.css
public/js/create.js
public/js/login.js
src/Views/_layout.phtml
src/Views/listings/create.phtml
src/Views/users/login.phtml

Website Intro Splash
